name: Dispatch announcements to Bazaar

on:
  discussion:
    types: [pinned]    

jobs:
 DispatchAnnouncement:
  runs-on: ubuntu-latest
  if: |
    github.event.discussion.category.name == 'Announcements' ||
    github.event.discussion.category.name == 'Releases' ||
    github.event.discussion.category.name == 'Research news' ||
    github.event.discussion.category.name == 'Schools and crash courses'
    
  steps:  
  - name: Fetch announcement
    id: announcement
    env:
      BODY: ${{ toJson(github.event.discussion.body) }}   
    run: |
      echo "::set-output name=category::${{ github.event.discussion.category.name }}"
      echo "::set-output name=title::${{ github.event.discussion.title }}"
      
      echo ${BODY} > body.txt
      echo "::set-output name=body::$(cat body.txt)"
      
  - name: Fetch current date
    id: date
    run: |
        echo "::set-output name=date::$(date +'%Y%m')"
        echo "::set-output name=date_spelled::$(date +'%B %Y')"

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1.1.3
    with:
      token: ${{ secrets.BAZAAR_ICUB_TECH_BOT_PAT }}
      repository: icub-tech-iit/code
      event-type: announcement_launched
      client-payload: '{"description": ${{ steps.announcement.outputs.body }}, "id": "${{ steps.date.outputs.date }}", "title": "${{ steps.announcement.outputs.title }}", "date": "${{ steps.date.outputs.date_spelled }}", "image": "???", "type" : "announcement_launched", "category": "${{ steps.announcement.outputs.category }}"}'
