name: Auto-upload Distro announcements to Bazaar

on:
  discussion:
    types: [pinned]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:
  
  - name: Fetch announcement
    id: announcement
    run: |
      category="${{ github.event.discussion.category.name }}"
      title="${{ github.event.discussion.title }}"
      body="${{ github.event.discussion.body }}"
      
      echo "::set-output name=title::${title}"
      echo "::set-output name=summary::${body:0:500}"
      echo "::set-output name=description::${body}"
      
      if [[ "${category}" == "Releases" ]]
      then
        echo "::set-output name=is_release::true"
      else
        echo "::set-output name=is_release::false"
      fi      

  - name: Fetch current date
    id: date
    run: |
        echo "::set-output name=date::$(date +'%Y%m')"
        echo "::set-output name=date_spelled::$(date +'%B %Y')"

  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1.1.3
    with:
      token: ${{ secrets.CODE_REPO_ACCESS_TOKEN }}
      repository: icub-tech-iit/code
      event-type: announcement_launched
      client-payload: '{"description": ${{ steps.announcement.outputs.description }}, "id": "${{ steps.date.outputs.date }}", "title": ${{ steps.announcement.outputs.title }}, "date": "${{ steps.date.outputs.date_spelled }}", "summary": "${{ steps.announcement.outputs.summary }}", "image": "???", "type" : "announcement_launched", "release": "${{ steps.announcement.outputs.is_release }}"}'
